sudo: false
language: node_js
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g coveralls
script:
- npm run test:coverage
- npm run dist
after_success:
- cat ./coverage/lcov.info | coveralls
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  # Only deploy the subfolder, not the whole repository.
  local_dir: examples
  # This value is stored below, encrypted with travis-encrypt.
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: Dp3ZtUx5O3v69zZk6M1TAA8HsDGA5VVpJSK7iXxK+q7/rBRmIOvfyUDRw+V4naXowgt4jKmIKKr5VUC9ItpIVkFr2t4Z8FL573WLuLpZUh2aGD3PW94GEax6WKpWNbsR4x31BMz7no3WX+WW4IuWO9m3pYIU+WD3mmNYXvEkgrs=
env:
  global:
    secure: yW0NwNqFb+SgWgRQBorFokhVGItx+QbB41HKR0MHXsgc3jUF4O2LixfPHo8T/mD8kIf+NWUYjI9ymrNYGqBorWQKzvdv+LoSnJaCFyqriGD0shT7jgp9J+ZN3gbL4wbcEFlK711DYa1D2pnQeObM/UeQWtQ6QkcwgFxMlQIp54Y=
